[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.04.37"
included-patches = "'Enable slide to seek' 'Remove player controls background'"
excluded-patches = "'Always repeat' 'Announcements' 'Enable debugging' 'Playback speed' 'External downloads' 'Disable player popup panels' 'Enable tablet layout' 'Wide searchbar' 'Tablet mini player' 'Hide captions button' 'Alternative thumbnails' 'Hide seekbar' 'Comments' 'Disable rolling number animations' 'Hide floating microphone button' 'Hide endscreen cards' 'Hide crowdfunding box' 'Disable suggested video end screen' 'Hide filter bar' 'Hide timestamp' 'Hide info cards' 'Return YouTube Dislike'"
