[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.04.37"
included-patches = "'Video ads' 'Hide ads' 'Minimized playback' 'GmsCore support' 'Restore old video quality menu' 'Remember video quality' 'Disable precise seeking gesture' 'Seekbar tapping' 'Remove viewer discretion dialog' 'Restore old seekbar thumbnails' 'Hide autoplay button' 'Hide cast button' 'Disable resuming Shorts on startup' 'Theme' 'Disable suggested video end screen' 'Disable auto captions'"
exclusive-patches = true
