logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false  # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "18.45.41"
included-patches = "'Hide ads' 'Video ads' 'Hide cast button' 'Hide autoplay button' 'Disable auto captions' 'Hide breaking news shelf' 'Player flyout menu' 'Disable suggested video end screen' 'Spoof app version' 'Theme' 'Restore old seekbar thumbnails' 'Client spoof' 'Spoof device dimensions' 'Vanced MicroG support' 'Minimized playback' 'Restore old video quality menu' 'Remember video quality' 'Swipe controls' 'Copy video url' 'Seekbar tapping' 'Disable precise seeking gesture' 'Enable slide to seek'"
exclusive-patches = true
