[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.16.39"
included-patches = "'Seekbar tapping' 'Enable slide to seek' 'Copy video URL' 'Theme' 'Hide cast button' 'Hide captions button' 'Disable suggested video end screen' 'Hide crowdfunding box' 'Hide filter bar' 'Hide endscreen cards' 'Change start page' 'Disable player popup panels' 'Spoof app version' 'Remove background playback restrictions' 'Disable zoom haptics' 'Bypass URL redirects' 'Check watch history domain name resolution' 'Remove tracking query parameter' 'GmsCore support' 'Spoof video streams' 'Video ads' 'Hide ads'"
exclusive-patches = true

