[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "20.12.46"
excluded-patches = "'Downloads' 'Disable rolling number animations' 'Hide timestamp' 'Return YouTube Dislike' 'Wide search bar' 'Spoof app version' 'Alternative thumbnails' 'Bypass image region restrictions' 'Announcements' 'Enable debugging' 'Spoof device dimensions' 'GmsCore support'"
