enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "19.47.53"
excluded-patches = "'Downloads' 'Hide seekbar' 'Hide timestamp' 'Return YouTube Dislike' 'Wide searchbar' 'Shorts autoplay' 'Spoof app version' 'Alternative thumbnails' 'Announcements' 'Always repeat' 'Enable debugging' 'Spoof device dimensions' 'GmsCore support'"
