logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "universal"
build-mode = "module"
version = "18.23.35"
module-prop-name = "ytrv-magisk-ted"
excluded-patches = "always-autorepeat client-spoof custom-branding disable-fullscreen-panels enable-debugging external-downloads hdr-auto-brightness hide-ads hide-captions-button hide-cast-button hide-crowdfunding-box hide-email-address hide-floating-microphone-button hide-load-more-button hide-player-overlay minimized-playback player-flyout-menu premium-heading return-youtube-dislike spoof-app-version tablet-mini-player vanced-microg-support video-ads wide-searchbar"
