[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "20.07.39"
excluded-patches = "'Downloads' 'Disable rolling number animations' 'Return YouTube Dislike' 'Wide search bar' 'Spoof app version' 'Alternative thumbnails' 'Announcements' 'Enable debugging' 'Spoof device dimensions' 'GmsCore support' 'Spoof video streams' 'Playback speed'"

