compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove its entry
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
enabled = true
build-mode = "module"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                        # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "copy-video-url disable-auto-captions disable-auto-player-popup-panels disable-startup-shorts-player general-ads hide-create-button hide-shorts-button hide-watermark minimized-playback old-quality-layout open-links-directly open-links-externally remember-video-quality sponsorblock swipe-controls theme video-ads hide-video-buttons disable-zoom-haptics hide-endscreen-cards remove-screenshot-restriction hdr-auto-brightness seekbar-tapping hide-watch-in-vr"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "18.05.40"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = true                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[Music-arm64]
enabled = false
build-mode = "apk"
app-name = "Music"
excluded-patches = ""
included-patches = "background-play codecs-unlock compact-header exclusive-audio-playback hide-get-premium minimized-playback-music music-microg-support music-video-ads upgrade-button-remover tasteBuilder-remover"
version = "5.39.52"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-magisk"
arch = "arm64-v8a"

[Music-arm]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-arm-magisk"
arch = "arm-v7a"

[Twitter]
enabled = false
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Reddit]
enabled = false
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Twitch]
enabled = false
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
enabled = false
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Spotify]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
