[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.16.39"
included-patches = "'Hide ads' 'Video ads' 'Bypass URL redirects' 'Spoof client' 'GmsCore support' 'Remove background playback restrictions' 'Theme' 'Restore old seekbar thumbnails' 'Miniplayer' 'Hide cast button' 'Hide autoplay button' 'Hide Shorts components' 'Disable suggested video end screen' 'Restore old video quality menu' 'Remember video quality' 'Swipe controls' 'Remove viewer discretion dialog'"
exclusive-patches = true

