enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "19.43.41"
excluded-patches = "'Downloads' 'Disable rolling number animations' 'Hide seekbar' 'Custom player overlay opacity' 'Return YouTube Dislike' 'Wide searchbar' 'Spoof app version' 'Enable tablet layout' 'Alternative thumbnails' 'Enable debugging' 'Spoof device dimensions' 'Spoof video streams' 'GmsCore support'"
