logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false  # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "18.45.41"
included-patches = "'Disable resuming Shorts on startup' 'Navigation buttons' 'Hide autoplay button' 'Hide video action buttons' 'Custom player overlay opacity' 'Disable auto captions' 'SponsorBlock' 'Hide floating microphone button' 'Disable fullscreen ambient mode' 'Hide 'Load more' button' 'Disable suggested video end screen' 'Hide Shorts components' 'Theme' 'Restore old seekbar thumbnails' 'Bypass URL redirects' 'Open links externally' 'Remove tracking query parameter' 'HDR auto brightness' 'Playback speed' 'Restore old video quality menu' 'Remember video quality' 'Swipe controls' 'Copy video url' 'Seekbar tapping' 'Disable precise seeking gesture' 'Enable slide to seek'"
exclusive-patches = true
