enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "19.04.37"
included-patches = "'Enable slide to seek'"
excluded-patches = "'Video ads' 'Spoof device dimensions' 'Always repeat' 'Minimized playback' 'Announcements' 'GmsCore support' 'Client spoof' 'External downloads' 'Enable tablet layout' 'Wide searchbar' 'Hide cast button' 'Alternative thumbnails' 'Spoof app version' 'Return YouTube Dislike'"
